import type { Context } from 'hono'
import type Stripe from 'stripe'

/**
 * One cart line, keyed by priceId — one line per Stripe price
 * (Alloy `cart_link.als`: DuplicatePriceInCart).
 */
export interface CartItem {
  /** Stripe price id (`price_...`). */
  priceId: string
  /** Absolute quantity, >= 1. `set` with quantity <= 0 removes the line. */
  quantity: number
  /**
   * Epoch seconds when the line was last written. Merge conflicts between
   * two carts resolve to the newer addedAt (Alloy: MergeConflict).
   */
  addedAt: number
}

/**
 * Storage boundary for carts on weak key-value stores.
 *
 * The verified layout in `spec/quint/cart_ops.qnt` is one key per line
 * (`cart:{id}:item:{priceId}`) so every mutation is a pure put or delete —
 * never read-modify-write. That is what keeps carts correct on
 * eventually-consistent stores (Workers KV, edge caches); adapters MUST
 * preserve these semantics.
 *
 * `list` may serve a stale view on weak stores. The known consequence is
 * the stale-charge hazard: checkout snapshots the served view and can
 * charge a line the user already removed (documented counterexample in
 * `spec/README.md` — `noStaleCharge`). Mitigate by confirming line items
 * server-side — Stripe Checkout's confirmation page already does this.
 *
 * Stores that expire lines (TTL'd carts, e.g. KV `expirationTtl`) add a
 * second hazard: a line can expire between snapshot and charge and still
 * be charged (`noExpiryCharge`). Bind any cart TTL far above the checkout
 * completion window — hours-to-days, never minutes.
 */
export interface CartStore {
  /** Enumerate a cart's lines. Weak stores may serve a stale view. */
  list(cartId: string): Promise<CartItem[]>
  /**
   * Absolute put of a single line. Implementations must not
   * read-modify-write — this is a pure put of a complete `CartItem`.
   */
  put(cartId: string, item: CartItem): Promise<void>
  /** Pure delete of a single line. */
  delete(cartId: string, priceId: string): Promise<void>
}

export type CartStoreResolver = CartStore | ((c: Context) => CartStore)

export const resolveCartStore = (
  store: CartStoreResolver,
  c: Context,
): CartStore => (typeof store === 'function' ? store(c) : store)

/** Line item shape stamped into checkout session params from the snapshot. */
export interface CartCheckoutLineItem {
  /** Stripe price id snapshotted at checkout time. */
  price: string
  quantity: number
}

/**
 * Params for `stripe.checkout.sessions.create`, generated by
 * `StripeCart.checkout`. Always `mode: 'payment'` — subscription carts are
 * out of scope (billing owns recurring linkage). `line_items` IS the
 * checkout snapshot: the same price ids `drain` deletes on completion.
 */
export interface CartCheckoutParams extends Stripe.Checkout.SessionCreateParams {
  mode: 'payment'
  line_items: CartCheckoutLineItem[]
}

/** Options for `StripeCart.checkout`. */
export interface CartCheckoutOptions {
  /**
   * Extra session params merged into the generated params —
   * `success_url`, `cancel_url`, shipping, taxes, etc. The structural
   * fields (`mode`, `line_items`, `client_reference_id`) are always
   * generated by the cart — omitted here so they cannot be passed.
   */
  params?: Omit<
    Stripe.Checkout.SessionCreateParams,
    'mode' | 'line_items' | 'client_reference_id'
  >
}

/** Result of `StripeCart.checkout` — the snapshot plus session params. */
export interface CartCheckout {
  /**
   * The snapshotted lines — possibly a stale view on weak stores (see the
   * stale-charge hazard on `CartStore`). Surface these server-side at
   * confirmation.
   */
  items: CartItem[]
  params: CartCheckoutParams
}
