packages:
  - examples/*
  - docs

allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: false
  workerd: true

minimumReleaseAgeExclude:
  - '@astrojs/starlight@0.42.5'
  - stripe-decline-codes@0.2.0
